#!/bin/bash

read -p "entrer un nom d'utilisateur a supprimer : " userd

if [ -z $userd ]
then
	echo "No user"
	exit
fi

if [ -n "$(who | grep $userd)" ]
then
	read -p "User $userd delete ? Confirm whit o/n : " confirm
	if [ "$confirm" == "o" ]
	then
		sudo killall -KILL -u $userd;
		sudo userdel -r $userd;
		echo "user $userd deleted"
		exit
	else
		echo "Process abort"
		exit
	fi
else
	echo "User does not exist or not connect"
	exit
fi
