#!/bin/bash

read -p "entrer un nom d'utilisateur a supprimer : " userd

if [ -z $userd ]
then
	echo "No user"
	exit
fi

if [ -n "$(whoami | grep $userd)" ]
then
	echo "StoooOOOOOPPP. YOU ARE $userd"
	exit
fi

if [ -n "$(who | grep $userd)" ]
then
	read -p "User $userd delete ? Confirm whit y/n : " confirm
	if [ "$confirm" == "y" ]
	then
		sudo passwd -l toto
		killall -KILL -u $userd
		sudo userdel -r $userd
		echo "user $userd deleted"
		exit
	else
		echo "Process abort"
		exit
	fi
else
	echo "User does not exist or not connect"
	exit
fi
